"""Species enumeration and rdkit 3D template generation.

Scope: C2-and-below C/H/O adsorbates plus the gas reference molecules demanded
by the Fe5C2(510) Fischer-Tropsch campaign (parent manifest, 2026-09-21).

Template contract (verified against the cluster gold standard
``$R/recnet-runs/ft2dpv22-demo-S/prepared_data/ads_templates/*.xyz``):

* plain extxyz, exactly what ``ase.io.write(..., format="extxyz")`` emits:
  line 1 = atom count, line 2 = ``Properties=species:S:1:pos:R:3 pbc="F F F"``,
  then ``symbol x y z`` with 8 decimals -- **no cell, no extra columns**;
* atom order is the rdkit atom order (heavy atoms first, hydrogens appended by
  ``Chem.AddHs``) so that ``ad_idx`` and ``broken_bond`` are stable indices into
  the template that ``handlers/ts.py`` reads with ``ase.io.read``.

Geometry is generated by ETKDGv3 with a fixed seed (deterministic for a pinned
rdkit version; the version is recorded in ``MANIFEST.json``).
"""

from __future__ import annotations

import io
from dataclasses import dataclass, field
from typing import Dict, Iterable, List, Sequence, Tuple

import numpy as np
from ase import Atoms
from ase.io import write as ase_write
from rdkit import Chem, RDLogger
from rdkit.Chem import AllChem, rdMolDescriptors

RDLogger.DisableLog("rdApp.*")

#: ETKDG random seed. Pinned so that repeated runs are byte-identical.
SEED = 20260921

#: Element pairs that define the channel space (parent manifest).
BOND_TYPES: Tuple[Tuple[str, str], ...] = (
    ("C", "H"),
    ("C", "C"),
    ("C", "O"),
    ("O", "H"),
    ("H", "H"),
)


@dataclass(frozen=True)
class SpeciesSpec:
    """Declarative species definition.

    ``ad_idx`` is *specified*, never inferred from geometry: it lists the
    template atom indices that anchor the species to a surface site
    (``handlers/context.py::_build_site_and_center_anchors``). Gas entries use
    an empty ``ad_idx``, which ``handlers/energy.py`` reads as "gas-capable".

    ``formula`` is the *independently declared* Hill formula. It is asserted
    against the rdkit-sensitive parse, which catches the classic SMILES trap:
    an unbracketed ``O`` with one bond silently picks up an implicit hydrogen
    (``[CH3]O`` parses as methanol, not methoxy).
    """

    key: str
    name: str
    group: str  # c1_ads | c2_ads | gas | closure
    smiles: str
    ad_idx: Tuple[int, ...]
    source: str  # manifest-required | closure (added by us)
    formula: str
    note: str = ""


@dataclass(frozen=True)
class Species:
    """A materialised species: template atoms plus graph metadata."""

    key: str
    name: str
    group: str
    smiles: str
    source: str
    note: str
    symbols: Tuple[str, ...]
    positions: Tuple[Tuple[float, float, float], ...]
    ad_idx: Tuple[int, ...]
    #: (i, j, bond_order) over template atom indices
    bonds: Tuple[Tuple[int, int, float], ...]
    identity: str
    counts: Dict[str, int] = field(default_factory=dict)

    @property
    def natoms(self) -> int:
        return len(self.symbols)

    @property
    def is_gas(self) -> bool:
        return len(self.ad_idx) == 0

    @property
    def formula(self) -> str:
        """Hill-order formula, e.g. ``C2H4`` / ``CH2O``."""
        order = [s for s in ("C", "H") if s in self.counts]
        order += sorted(s for s in self.counts if s not in order)
        return "".join(
            f"{s}{self.counts[s]}" if self.counts[s] != 1 else s for s in order
        )

    @property
    def edges(self) -> Tuple[Tuple[int, int], ...]:
        """Bond connectivity ignoring bond order (order is metadata only)."""
        return tuple((i, j) for i, j, _ in self.bonds)


# ---------------------------------------------------------------------------
# Species table
# ---------------------------------------------------------------------------
# Order matters: it fixes sp_xxx numbering and therefore the yaml line order.
# ``source`` keeps the provenance auditable: everything that is not
# "manifest-required" was added by us for fragment closure / paper coverage.

SPECS: Tuple[SpeciesSpec, ...] = (
    # ---- C1 adsorbates (manifest-required) -------------------------------
    SpeciesSpec("C", "C", "c1_ads", "[C]", (0,), "manifest-required", "C",
                "atomic carbon"),
    SpeciesSpec("CH", "CH", "c1_ads", "[CH]", (0,), "manifest-required", "CH",
                "methylidyne"),
    SpeciesSpec("CH2", "CH2", "c1_ads", "[CH2]", (0,), "manifest-required", "CH2",
                "methylene"),
    SpeciesSpec("CH3", "CH3", "c1_ads", "[CH3]", (0,), "manifest-required", "CH3",
                "methyl"),
    SpeciesSpec("CO", "CO", "c1_ads", "[C-]#[O+]", (0,), "manifest-required", "CO",
                "C-bound CO, ad_idx [0] matches the cluster gold standard demo"),
    SpeciesSpec("COH", "COH", "c1_ads", "[C]O", (0,), "manifest-required", "CHO",
                "H on oxygen (hydroxycarbene); distinguishes it from HCO"),
    SpeciesSpec("HCO", "HCO", "c1_ads", "[CH]=O", (0,), "manifest-required", "CHO",
                "formyl, H on carbon"),
    SpeciesSpec("H2CO", "H2CO", "c1_ads", "C=O", (0,), "manifest-required", "CH2O",
                "formaldehyde"),
    SpeciesSpec("H3CO", "H3CO", "c1_ads", "[CH3][O]", (0,), "manifest-required", "CH3O",
                "methoxy (bracketed O keeps the radical; '[CH3]O' would be methanol)"),
    SpeciesSpec("O", "O", "c1_ads", "[O]", (0,), "manifest-required", "O",
                "atomic oxygen"),
    SpeciesSpec("OH", "OH", "c1_ads", "[OH]", (0,), "manifest-required", "HO",
                "hydroxyl, O-bound"),
    # ---- C2 adsorbates (manifest-required) -------------------------------
    SpeciesSpec("CC", "CC", "c2_ads", "[C]#[C]", (0, 1), "manifest-required", "C2",
                "dicarbon, both carbons bind"),
    SpeciesSpec("CCH", "CCH", "c2_ads", "[CH]#[C]", (1,), "manifest-required", "C2H",
                "ethynyl, binds through the bare carbon"),
    SpeciesSpec("CCH2", "CCH2", "c2_ads", "[CH2]=[C]", (1,), "manifest-required", "C2H2",
                "vinylidene, binds through the bare carbon"),
    SpeciesSpec("CCH3", "CCH3", "c2_ads", "[CH3][C]", (1,), "manifest-required", "C2H3",
                "ethylidyne, binds through the bare carbon"),
    SpeciesSpec("CHCH", "CHCH", "c2_ads", "[CH]#[CH]", (0, 1), "manifest-required", "C2H2",
                "acetylene, di-sigma binding"),
    SpeciesSpec("CHCH2", "CHCH2", "c2_ads", "[CH2]=[CH]", (0, 1), "manifest-required", "C2H3",
                "vinyl, di-sigma binding"),
    SpeciesSpec("CH2CH2", "CH2CH2", "c2_ads", "C=C", (0, 1), "manifest-required", "C2H4",
                "adsorbed ethylene, di-sigma binding"),
    SpeciesSpec("CH2CH3", "CH2CH3", "c2_ads", "C[CH2]", (1,), "manifest-required", "C2H5",
                "ethyl, binds through the CH2 carbon"),
    SpeciesSpec("CCO", "CCO", "c2_ads", "[C]=C=O", (0,), "manifest-required", "C2O",
                "ketenylidene (C2O)"),
    SpeciesSpec("CHCO", "CHCO", "c2_ads", "[CH]=C=O", (0, 1), "manifest-required", "C2HO",
                "ketenyl (C2HO), C=C end binds"),
    SpeciesSpec("CH2CO", "CH2CO", "c2_ads", "C=C=O", (0, 1), "manifest-required", "C2H2O",
                "ketene (C2H2O), C=C end binds"),
    # ---- gas references (manifest-required, ad_idx == []) ----------------
    SpeciesSpec("H2", "H2", "gas", "[H][H]", (), "manifest-required", "H2",
                "gas reference; also the H-H scission precursor"),
    SpeciesSpec("H2O", "H2O", "gas", "O", (), "manifest-required", "H2O",
                "gas reference; only entry for water in the table"),
    SpeciesSpec("CH4", "CH4", "gas", "C", (), "manifest-required", "CH4",
                "gas reference; only entry for methane (needed by the paper "
                "C-CH4 dehydrogenation ladder)"),
    SpeciesSpec("C2H4", "C2H4", "gas", "C=C", (), "manifest-required", "C2H4",
                "gas reference for C2H4; same molecule as adsorbed CH2CH2, "
                "which owns the channels (see identity dedup)"),
    SpeciesSpec("C2H6", "C2H6", "gas", "CC", (), "manifest-required", "C2H6",
                "gas reference for ethane; only entry for C2H6"),
    SpeciesSpec("CO_GAS", "CO", "gas", "[C-]#[O+]", (), "manifest-required", "CO",
                "gas reference for CO; same molecule as CO* (ad_idx [0]), and "
                "handlers/energy.py force-lists name 'CO' as gas-capable"),
    # ---- closure additions (NOT in the manifest list) ---------------------
    SpeciesSpec("H", "H", "closure", "[H]", (0,), "closure", "H",
                "atomic hydrogen: product of every C-H / O-H / H-H scission"),
)


# ---------------------------------------------------------------------------
# Graph identity
# ---------------------------------------------------------------------------


def identity_key(symbols: Sequence[str], edges: Iterable[Tuple[int, int]]) -> str:
    """Order-agnostic canonical key for an H-explicit connectivity graph.

    Bond orders are deliberately excluded: ``handlers/context.py`` and
    ``handlers/ts.py`` detect bonds from interatomic distances only (covalent
    radii x 1.2), so bond order never reaches the pipeline. Hydrogen atoms are
    explicit graph nodes, which is what separates isomers such as HCO (H on C)
    from COH (H on O), or CCH2 from CHCH.
    """
    symbols = tuple(symbols)
    edge_set = {tuple(sorted((int(i), int(j)))) for i, j in edges}
    n = len(symbols)
    adjacency: List[List[int]] = [[] for _ in range(n)]
    for i, j in sorted(edge_set):
        adjacency[i].append(j)
        adjacency[j].append(i)

    colors = list(symbols)
    for _ in range(max(1, n)):
        signature = [
            colors[i] + "(" + "".join(sorted(colors[j] for j in adjacency[i])) + ")"
            for i in range(n)
        ]
        ranks = {value: rank for rank, value in enumerate(sorted(set(signature)))}
        colors = [str(ranks[value]) for value in signature]

    labels = [f"{symbols[i]}:{colors[i]}" for i in range(n)]
    node_part = ",".join(sorted(labels))
    edge_part = ",".join(
        sorted("-".join(sorted((labels[i], labels[j]))) for i, j in sorted(edge_set))
    )
    return f"N[{node_part}]E[{edge_part}]"


def fragment_identity(symbols: Sequence[str], edges: Iterable[Tuple[int, int]],
                      keep: Sequence[int]) -> str:
    """Identity of the sub-graph induced by ``keep`` (relabelled 0..k-1)."""
    keep = list(keep)
    local = {atom: idx for idx, atom in enumerate(keep)}
    sub_symbols = [symbols[atom] for atom in keep]
    sub_edges = [
        (local[i], local[j])
        for i, j in edges
        if i in local and j in local
    ]
    return identity_key(sub_symbols, sub_edges)


def split_fragments(n: int, edges: Iterable[Tuple[int, int]], cut: Tuple[int, int]):
    """Connected components after removing the ``cut`` edge."""
    adjacency: List[List[int]] = [[] for _ in range(n)]
    for i, j in edges:
        if tuple(sorted((i, j))) == tuple(sorted(cut)):
            continue
        adjacency[i].append(j)
        adjacency[j].append(i)

    seen = set()
    components: List[List[int]] = []
    for start in range(n):
        if start in seen:
            continue
        stack = [start]
        seen.add(start)
        comp = []
        while stack:
            node = stack.pop()
            comp.append(node)
            for neighbor in adjacency[node]:
                if neighbor not in seen:
                    seen.add(neighbor)
                    stack.append(neighbor)
        components.append(sorted(comp))
    return sorted(components)


# ---------------------------------------------------------------------------
# Materialisation
# ---------------------------------------------------------------------------


def _rdkit_mol(smiles: str) -> Chem.Mol:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"rdkit could not parse SMILES {smiles!r}")
    return Chem.AddHs(mol)


def _embed(mol: Chem.Mol, seed: int) -> np.ndarray:
    """Deterministic 3D coordinates; single atoms sit at the origin."""
    n = mol.GetNumAtoms()
    if n == 1:
        return np.zeros((1, 3))
    params = AllChem.ETKDGv3()
    params.randomSeed = seed
    conf_id = AllChem.EmbedMolecule(mol, params)
    if conf_id < 0:
        params.useRandomCoords = True
        conf_id = AllChem.EmbedMolecule(mol, params)
    if conf_id < 0:
        raise RuntimeError(f"rdkit ETKDG failed to embed {Chem.MolToSmiles(mol)!r}")
    return np.array(mol.GetConformer(conf_id).GetPositions(), dtype=float)


def _materialise(spec: SpeciesSpec, seed: int) -> Species:
    mol = _rdkit_mol(spec.smiles)
    positions = _embed(mol, seed)
    symbols = tuple(atom.GetSymbol() for atom in mol.GetAtoms())
    bonds = tuple(
        (bond.GetBeginAtomIdx(), bond.GetEndAtomIdx(), float(bond.GetBondTypeAsDouble()))
        for bond in mol.GetBonds()
    )

    counts: Dict[str, int] = {}
    for symbol in symbols:
        counts[symbol] = counts.get(symbol, 0) + 1

    # Cross-check three independent sources: the declared spec formula, rdkit's
    # perception of the SMILES, and the element counts of the embedded atoms.
    formula_rdkit = rdMolDescriptors.CalcMolFormula(mol)
    formula_from_graph = "".join(
        f"{s}{counts[s]}" if counts[s] != 1 else s
        for s in sorted(counts, key=lambda s: (s != "C", s != "H", s))
    )
    for label, value in (("rdkit", formula_rdkit), ("atoms", formula_from_graph)):
        if value != spec.formula:
            raise AssertionError(
                f"{spec.key}: declared formula {spec.formula} != {label} formula {value} "
                f"(SMILES {spec.smiles!r})"
            )

    ad_idx = tuple(int(i) for i in spec.ad_idx)
    has_heavy_atom = any(symbol != "H" for symbol in symbols)
    for idx in ad_idx:
        if not 0 <= idx < len(symbols):
            raise AssertionError(f"{spec.key}: ad_idx {idx} out of range")
        # Adsorption anchors must be heavy atoms; the atomic-H adsorbate is the
        # documented exception because it has no heavy atom at all.
        if symbols[idx] == "H" and has_heavy_atom:
            raise AssertionError(f"{spec.key}: ad_idx {idx} points at hydrogen")
    if sorted(set(ad_idx)) != sorted(ad_idx):
        raise AssertionError(f"{spec.key}: ad_idx has duplicates: {ad_idx}")

    # Centre the anchor atoms (or the whole molecule for gas entries) on the
    # origin so that the pipeline's site translation starts from a defined pose.
    centre = positions[list(ad_idx)].mean(axis=0) if ad_idx else positions.mean(axis=0)
    positions = positions - centre

    identity = identity_key(symbols, [(i, j) for i, j, _ in bonds])
    return Species(
        key=spec.key,
        name=spec.name,
        group=spec.group,
        smiles=spec.smiles,
        source=spec.source,
        note=spec.note,
        symbols=symbols,
        positions=tuple(tuple(float(value) for value in row) for row in positions),
        ad_idx=ad_idx,
        bonds=bonds,
        identity=identity,
        counts=counts,
    )


def build_species_table(seed: int = SEED, expansion: bool = False,
                        expansion2: bool = False, expansion3: bool = False,
                        expansion4: bool = False, expansion5: bool = False,
                        expansion6: bool = False,
                        expansion6_tier: str = "closed-shell") -> List[Species]:
    """Materialise every declared species in declaration order.

    ``expansion=True`` appends the closure-round-1 species table
    (:mod:`network_builder.expansion`) **after** the frozen 29 entries, so
    ``sp_xxx`` ids of the frozen table do not move. Default ``False`` keeps the
    frozen dataset byte-identical.

    ``expansion6=True`` appends the C3 closure gaps (:mod:`network_builder.expansion6`,
    2026-09-26 R309) — again **after** everything else, and gated by
    ``expansion6_tier`` (default ``"closed-shell"``, the chemically clean tier;
    ``"all"`` includes doubly-dangling species that still need chemical review).
    """
    specs = tuple(SPECS)
    if expansion or expansion2 or expansion3 or expansion4:
        # 局部导入：默认路径不引入扩展依赖
        from .expansion import EXPANSION_SPECS

        specs = specs + tuple(EXPANSION_SPECS)
    if expansion2:
        from .expansion2 import EXPANSION2_SPECS

        specs = specs + tuple(EXPANSION2_SPECS)
    if expansion3:
        from .expansion3 import EXPANSION3_SPECS

        specs = specs + tuple(EXPANSION3_SPECS)
    if expansion4:
        # 2026-09-25 (R175): closure-completion round — the 7 residual products found by the
        # wave-4 (option c) audit (network_builder/expansion4.py).
        from .expansion4 import EXPANSION4_SPECS

        specs = specs + tuple(EXPANSION4_SPECS)
    if expansion5:
        # 2026-09-25 (R226): scission-residue round — CO2 (gas), the only clean closed-shell
        # fragment of the 76 dropped cuts (network_builder/expansion5.py).
        from .expansion5 import EXPANSION5_SPECS

        specs = specs + tuple(EXPANSION5_SPECS)
    if expansion6:
        # 2026-09-26 (R309): C3 扩网 wave-1 —— 由 closure_audit --max-c 3 机械给出的 C3 缺口，
        # 按档取子集（默认 closed-shell；all 档含双悬挂价物种，需化学评审）。
        from .expansion6 import specs_for_tier

        specs = specs + tuple(specs_for_tier(expansion6_tier))
    return [_materialise(spec, seed) for spec in specs]


def template_text(species: Species) -> str:
    """extxyz text for one template, byte-compatible with the gold standard."""
    atoms = Atoms(
        symbols="".join(species.symbols),
        positions=np.array(species.positions, dtype=float),
        pbc=False,
    )
    buffer = io.StringIO()
    ase_write(buffer, atoms, format="extxyz")
    return buffer.getvalue()
